

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/weixin?characterEncoding=utf-8&useSSL=false
    username: root
    password: cqmyg@212406
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell


wechat:
  mpAppId: wxb7855b4907d34564
  mpAppSecret: 0cae0c81c3d001b0cf35a0da8fa4950f
  mchId: 111
  mchKey: 222
  keyPath: /var/weixin_path/h5.p12
  notifyUrl: http://xxx.cc/sell/pay/notify